ALTER TABLE referral_codes
ADD COLUMN IF NOT EXISTS bonus_new_user NUMERIC(14,2) NOT NULL DEFAULT 100,
ADD COLUMN IF NOT EXISTS bonus_referrer NUMERIC(14,2) NOT NULL DEFAULT 100,
ADD COLUMN IF NOT EXISTS max_uses INTEGER,
ADD COLUMN IF NOT EXISTS uses_count INTEGER NOT NULL DEFAULT 0;
